### ISSUE TITLE
UCD list in tex not in sync with ucd-list.txt

### ISSUE THREAD

**Issue by loumir** [ivoa-std/UCDList#53]
Is there a way to automize the insertion of the python script formatting the content 
of ucd-list.txt in the workflow? 

Currently the content in the pdf is the one from the previous version , while the ucd-list.txt is the correct updated version.

**Comment by BaptisteCecconi** [comment]
Yes, I think you should add a `make generate` command. I can't check right now

**Comment by msdemlei** [comment]
On Tue, May 03, 2022 at 09:24:09AM -0700, Baptiste Cecconi wrote:
> Yes, I think you should add a `make generate` command. I can't check right now

Exactly: in order to keep the amount of magic at a minimum, document
generation in ivoatex needs to be explicitly started; in addition to
the magic thing, make generate often needs extra software or a
network connection, and if it were automatic, that would increase the
number of dependencies required for building the document, and
there's too many of those as-is.

Perhaps we ought to say:

  When you change ucd-list.txt, run a make generate.

in the README?  Or somewhere else?

I've thought about putting it as a comment in ucd-list.txt, but no,
let's not do that, as all consumers would then have to start skipping
comments (and the comment would be entirely inappropriate for them).

**Comment by BaptisteCecconi** [comment]
I have included the `make generate` command in the gitlab workflow. Since it implies a rather simple python script, that is fine I guess (and it runs).
