### ISSUE TITLE
how to link the ucd-list.txt and ucd-list-deprecated.txt to its release number

### ISSUE THREAD

**Issue by loumir** [ivoa-std/UCDList#69]
the function \auxiliary url binds these files to some ivoa wiki page , but goes on error. 

how can we associate the two files to each version of the EN-UCDList-X.Y release? 
thanks , ML

**Comment by msdemlei** [comment]
On Mon, Jun 27, 2022 at 11:21:33AM -0700, Mireille LOUYS wrote:
> the function \auxiliary url binds these files to some ivoa wiki
> page , but goes on error. 

What exactly do you mean with "goes on error"?  If you mean "does not
resolve", that is no reason to worry: The links point to where the
files *will* be once installed.  Before the document is uploaded,
these links will return 404s.

However, now that I look I notice that regrettably, the UCD list has
a non-standard base URI; it should be
https://ivoa.net/documents/UCDlist by our normal systematics (based
on the DOCNAME) but it really is https://ivoa.net/documents/UCD1+.
Hence, to make sure the URLs will work after uploading, you need to
add

DOCREPO_BASEURL=https://ivoa.net/documents/UCD1+

to the UCDlist's Makefile.  Being able to override the basic URLs is
a rather new feature in ivoatex; be sure to run

  make update

to get the latest ivoatex version before re-building.

**Comment by msdemlei** [comment]
On Thu, Jul 07, 2022 at 09:27:26AM -0700, Mireille LOUYS wrote:
> the function \auxiliaryurl did not work in our trials even when
> DOCREPO_BASEURL is set in the Makefile .

Ah... that would have been because that feature only went in through
PR#83, for which I had hoped for a review.

I've now force-merged it, so after a 

  make update; make clean; make

auxiliaryurl will work as advertised.

Sorry for having forgotten about this PR; on the other hand: folks,
please watch ivoatex and review PRs there.
