### ISSUE TITLE
ucd-list.txt has no version number in the file 

### ISSUE THREAD

**Issue by loumir** [ivoa-std/UCDList#74]
as far as I understand, the only way to know the versionof the spec corresponding to the ucd-list.txt file is by looking on the appropriate branch in the git repo. 
but when I copy the list or hand it over to some program or colleague , the version information is lost . 
I would like it to be written in the first line of the file , or in the file name . 

however it seems the 'generate' scripts cannot handle the lines with #
any suggestion to proceed?

**Comment by BaptisteCecconi** [comment]
I tend to agree with Markus. Unless this is automated, I would not duplicate the version information in many files, with the risk of forgetting to update them.

**Comment by loumir** [comment]
[https://www.ivoa.net/documents/UCD1+/20220706/ucd-list.txt](https://www.ivoa.net/documents/UCD1+/20220706/ucd-list.txt)
 this is the link to the list of term for the UCD1.5 version as stated in the PEN_UCDList1.5 document. 

There is no indication of the version number. 
It means that to check to which version the file belongs  you must go to some server , ivoa documents , git , etc . and compare the list . 
I think we can save some user and computer time, and also energy by just adding a version tag. 
There are real people working with theses files, tagging data columns with theses terms at the archive level and we should think on the way we can ease their task.

**Comment by BaptisteCecconi** [comment]
We could add a script, triggered by `make generate`, which would add the detailed version number in a first row (hash-commented line). Then it is automated, and using the relevant metadata stored in the `Makefile`.

**Comment by msdemlei** [comment]
On Fri, Jul 08, 2022 at 05:48:29AM -0700, Baptiste Cecconi wrote:
> We could add a script, triggered by `make generate`, which would
> add the detailed version number in a first row (hash-commented
> line). Then it is automated, and using the relevant metadata stored
> in the `Makefile`.

Sure, but 

(a) what would this buy us?  I still maintain people should just pull
the latest UCD list when something seems fishy -- how would that be
different if there's a version in the file?  I don't think anyone
will say "Aw, that's version 1.5-pre-1.6-20220523, that's good
enough".

(b) more relevantly, who will curse us because their UCD list parsers
suddenly fail after they pulled a new version of the UCD list?

(c) Finally, again: if we bother to do that, we'll have to define and
document the format of that version string, in particular for edits
between the releases: would it be a date?  a git sha1 hash? something
we just count up like a patch level?  Micro versions?

**Comment by msdemlei** [comment]
On Fri, Jul 08, 2022 at 02:33:04AM -0700, Mireille LOUYS wrote:
> There is no indication of the version number. 
> It means that to check to which version the file belongs  you must
> go to some server , ivoa documents , git , etc . and compare the
> list . 

But when would you have to do that?  I suspect if we better
understand the problem you're trying to solve we might be able to
find a better solution.

> There are real people working with theses files, tagging data
> columns with theses terms at the archive level and we should think
> on the way we can ease their task.

Sure -- but that's exactly the reason why we shouldn't
light-heartedly change the file's format...
